service: indra-rimac-challenge

frameworkVersion: '>=4.0.0 <5.0.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  deploymentBucket:
    name: indra-rimac-challenge-bucket
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    STAGE: ${opt:stage, 'dev'}

functions:
  createCharacter:
    handler: dist/infrastructure/handlers/characterHandler.createCharacterHandler
    events:
      - http:
          path: characters
          method: post

  getCharacters:
    handler: dist/infrastructure/handlers/characterHandler.getCharactersHandler
    events:
      - http:
          path: characters
          method: get

  swagger:
    handler: dist/infrastructure/handlers/swaggerHandler.handler
    events:
      - http:
          path: api-docs
          method: get

resources:
  Resources:
    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package:
  individually: true
  exclude:
    - node_modules/**
    - dist/**
    - .git/**
    - .vscode/**
    - '*.md'
    - .env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001
